name: gp_login_screen
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  device_preview: ^0.4.4
  cached_network_image: ^2.1.0+1
  sliding_up_panel: ^1.0.2
  flutter_credit_card: ^0.1.1
  flutter_svg: ^0.17.4
  provider: ^3.0.0
  flutter_speed_dial: ^1.2.5
  http: ^0.12.0+2
  dio: ^3.0.9
  shared_preferences: any
  barcode_scan: ^3.0.1
  date_format: ^1.0.8
  flutter_tags: "^0.4.8+2"
  searchable_dropdown: ^1.1.3
  carousel_slider: ^2.2.1
  charts_flutter: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - drawables/Logo.png
    - drawables/HELLO.png
    - drawables/facebook.png
    - drawables/google.png
    - drawables/back_btn.png
    - drawables/register1.png
    - drawables/circle-em.png
    - drawables/circle-em2.png
    - drawables/circle-30.png
    - drawables/Line1.png
    - drawables/Line2.png
    - drawables/checkmark-30.png
    - drawables/Account.png
    - drawables/Scanner.png
    - drawables/flash.png
    - drawables/scan.png
    - drawables/home.png
    - drawables/edit.png
    - drawables/list.png
    - drawables/homei.png
    - drawables/back.png
    - drawables/barcode.png
    - drawables/cart.png
    - drawables/settings.png
    - drawables/order.png
    - drawables/cardbg-blue.png
    - assets/credit-card.svg
    - assets/payment-method.svg
    - assets/transfere.svg
    - assets/sim.svg
    - assets/visa.svg
    - assets/drawer-icon.svg
    - assets/scanner.svg
    - assets/hot sale.svg
    - assets/like.svg
    - assets/party.svg

  #  - drawables/a_dot_burr.jpeg
  #  - drawables/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-drawables/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-drawables/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
          #style: italic

    #- family: Trajan Pro
    # fonts:
    #  - asset: fonts/TrajanPro.ttf
    #  - asset: fonts/TrajanPro_Bold.ttf
    #    weight: 700
  #fonts:
  #- family:
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
